#!/usr/bin/env bash
# customizing 404 page that contains the string Ceci n'est pas une page
sudo apt-get update -y
sudo apt-get install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error404.html
sudo sed -i '25i\	error_page 404 /error404.html;' /etc/nginx/sites-available/default

sudo service nginx restart
