#!/usr/bin/env bash
# configures an Nginx server to be running, and listening on port 80
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
kill "$(pgrep 'nginx' | head -l)"
